[default]
extend-ignore-re = [
  # nvim doc strings
  " \\[[sS]\\]tage ",
  "'\\[S\\]earch[' ]",
  " \\[[I]\\]nner ",
  " \\[R\\]eferences'",
  " \\[S\\]ymbols'",
  # fx-private-relay docs/workspace.json
  "replys \\[sic\\]",
]

[default.extend-identifiers]
KMS = "KMS"

[type.py.extend-identifiers]
email_for_dne_subdomain = "email_for_dne_subdomain"

[type.md]
extend-glob = ["*.md"]
extend-ignore-re = [
  # People
  "\\b*Wil\\s+Clouser\\b",
  "\\b*Lindsey\\s+Shepard\\b",
]
